production:
  clients:
    default:
      database: bookmaker_production
      hosts:
        - db:27017
      options:
        user: 'mongoroot'
        password: 'mongosecret'
        read:
          mode: :primary
        max_pool_size: 1
development:
  clients:
    default:
      database: bookmaker_development
      hosts:
        - db:27017
      options:
  options:
    raise_not_found_error: true
test:
  clients:
    default:
      database: bookmaker_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
