version: '3.8'
services:
  db:
    image: mongo:4.4.3
    restart: always
    #environment:
      # mongodb client connection
      #MONGO_INITDB_ROOT_USERNAME: mongoroot
      #MONGO_INITDB_ROOT_PASSWORD: mongosecret
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ".:/app"
volumes:
  dbdata:
